- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 392749559832.dkr.ecr.ap-south-1.amazonaws.com
      docker stop secondbrain-backend || true
      docker rm secondbrain-backend || true
      docker pull 392749559832.dkr.ecr.ap-south-1.amazonaws.com/secondbrain-backend:latest
      docker run -d -p 8080:8080 \
        --name secondbrain-backend \
        -e SPRING_PROFILES_ACTIVE=prod \
        -e APP_CORS_ALLOWED_ORIGINS=http://secondbrain-frontend-tanmay.s3-website.ap-south-1.amazonaws.com \
        -e SPRING_DATASOURCE_URL=jdbc:postgresql://portfolio-db.cdqei2mkmdor.ap-south-1.rds.amazonaws.com:5432/secondbrain_db \
        -e SPRING_DATASOURCE_USERNAME=postgres \
        -e SPRING_DATASOURCE_PASSWORD='vCpVDwlfkQhYtSSQrEX9' \
        -e SPRING_AI_GOOGLE_GEMINI_API_KEY='AIzaSyDK622J_FZ4nXGjxYCBa5vrwVAhajq8oME' \
        392749559832.dkr.ecr.ap-south-1.amazonaws.com/secondbrain-backend:latest